---
# tasks file for commons

#
# Loading variables
###################################
- include_vars: file='{{ ansible_os_family }}/packages.yml'

#
# Installing packages
###################################
- include: '{{ ansible_os_family }}/package.yml'

#
# Configuring the machine
###################################
- include: nodistro/datetime.yml
- include: nodistro/hostname.yml
- include: nodistro/service.yml
