# Here we will download some packages that are needed to use on a Debian or
# Ubuntu server, and ensure that every package is up to date. This playbook
# will not try to install or configure the SELinux on a Debian-like because
# they don't support the service out-of-box.

- name: Download all the default packages for Ubuntu/Debian System
  apt: pkg={{ basic }} state=installed

# For you can use this guy everytime, we will set the upgrade activity for safe.
# This option is the equivalent for apt-get upgrade
- name: Updating all the packages for Ubuntu/Debian System
  apt: upgrade=dist
