# Here we will download some packages that are needed to use on a Red Hat
# Enterprise Linux or CentOS server, and ensure that every package is up to date.
# The package libselinux-python need to be installed for ansible work correctly
# with the SELinux. The deltarpm is for less download during the update step.
# All the packages are ensured to be the latest, and this will only change if
# there is a motive behind this.

- name: Download all the default packages for CentOS/RHEL System
  yum: name={{ basic }} state=installed

- name: Updating all the packages for CentOS/RHEL System
  yum: name=* state=latest
